---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.egarciam.com
  resources:
  - canaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.egarciam.com
  resources:
  - canaries/finalizers
  verbs:
  - update
- apiGroups:
  - apps.egarciam.com
  resources:
  - canaries/status
  verbs:
  - get
  - patch
  - update
