apiVersion: apps.egarciam.com/v1alpha1
kind: Canary
metadata:
  labels:
    app.kubernetes.io/name: canary
    app.kubernetes.io/instance: canary-sample
    app.kubernetes.io/part-of: my-canary-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: my-canary-operator
  name: canary-sample
spec:
  # TODO(user): Add fields here
